name: 'Keyphrase Checker'
description:
  'Checks for the presence of a specific phrase in text content or a file'
author: 'GitHub Skills'

inputs:
  text-file:
    description: 'Path to a file containing text to check'
    required: false
  text:
    description: 'Direct text input to check'
    required: false
  keyphrase:
    description: 'The phrase to search for in the text'
    required: true
  case-sensitive:
    description: 'Whether to perform case-sensitive matching'
    required: true
    default: 'false'
  minimum-occurrences:
    description: 'Minimum number of occurrences required for success'
    required: true
    default: '1'

outputs:
  occurrences:
    description: 'Number of occurrences of the keyphrase found in the text'

runs:
  using: 'node20'
  main: 'dist/index.js'
